# Generated by Django 3.2.5 on 2023-09-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Short name for the affiliation', max_length=200)),
                ('long_name', models.CharField(help_text='Long name for the affiliation', max_length=200)),
                ('country', models.CharField(help_text='Country of the of affiliation', max_length=200)),
                ('department', models.CharField(blank=True, default='', help_text='Department name of the affiliation', max_length=200)),
                ('institute', models.CharField(blank=True, help_text='Name of the institute for the affiliation', max_length=200)),
                ('laboratory', models.CharField(blank=True, help_text='Name of the laboratory for the affiliation', max_length=200)),
                ('laboratory_internal', models.CharField(blank=True, help_text='Internal name of the laboratory for the affiliation', max_length=200)),
            ],
            options={
                'ordering': ['short_name', 'laboratory'],
            },
        ),
        migrations.CreateModel(
            name='ContributionOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Origin of the contribution', max_length=200)),
            ],
            options={
                'verbose_name': 'Origin of the contribution',
                'verbose_name_plural': 'Origin of the contributions',
            },
        ),
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Type of contribution', max_length=200)),
            ],
            options={
                'verbose_name': 'Type of contribution',
                'verbose_name_plural': 'Type of contributions',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('orcid', models.CharField(blank=True, default='', help_text='Provide 16 digits orcid in the form: 0000-0000-0000-0000', max_length=19)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('affiliation', models.ManyToManyField(help_text='Select one or several affiliation for this contributor', to='contribution_catalog.Affiliation')),
                ('person', models.ForeignKey(help_text='Select one person', on_delete=django.db.models.deletion.CASCADE, to='contribution_catalog.person')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the contribution for this contributor', max_length=2000)),
                ('contributor', models.ManyToManyField(help_text='Select a contributor', to='contribution_catalog.Contributor')),
                ('origin', models.ManyToManyField(help_text='Select one or several origin of contribution for this contributor', to='contribution_catalog.ContributionOrigin')),
                ('type', models.ManyToManyField(help_text='Select one or several type of contribution for this contributor', to='contribution_catalog.ContributionType')),
            ],
        ),
    ]
