# Generated by Django 3.2.5 on 2023-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution_catalog', '0001_initial'),
        ('project_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contribution',
            field=models.ManyToManyField(blank=True, help_text='Contribution(s) for this project', to='contribution_catalog.Contribution'),
        ),
    ]
