# Generated by Django 3.2.5 on 2023-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentalcondition_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='mutation',
            field=models.ManyToManyField(default='', help_text='mutation', to='experimentalcondition_catalog.Mutation'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mutation_grade',
            field=models.ManyToManyField(default='', help_text='mutation grade', to='experimentalcondition_catalog.MutationGrade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parent_line',
            field=models.ManyToManyField(default='', help_text='Parents fish lines', to='experimentalcondition_catalog.ParentLine'),
        ),
    ]
