# Generated by Django 3.2.5 on 2023-09-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdataset',
            old_name='rcp_name',
            new_name='data_name',
        ),
    ]
