# Generated by Django 3.2.5 on 2023-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0002_rename_rcp_name_rawdataset_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdataset',
            name='date_removed',
            field=models.DateField(help_text='Date when the rawdataset is removed from RCP', null=True),
        ),
    ]
