# Generated by Django 3.2.5 on 2023-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0026_labcontributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Short name for the affiliation', max_length=200)),
                ('long_name', models.CharField(help_text='Long name for the affiliation', max_length=200)),
                ('country', models.CharField(help_text='country of the laboratory of affiliation', max_length=200)),
            ],
        ),
    ]
