# Generated by Django 3.2.5 on 2023-07-31 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0027_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='institute_name',
            field=models.CharField(default='toto', help_text='Name of the institute for the affiliation', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labcontributor',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rawdata_catalog.affiliation'),
        ),
    ]
