# Generated by Django 3.2.5 on 2023-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0029_affiliation_laboratory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labcontributor',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='labcontributor',
            name='affiliation',
            field=models.ManyToManyField(help_text='Select an affiliation for this contributor', to='rawdata_catalog.Affiliation'),
        ),
    ]
