# Generated by Django 3.2.5 on 2023-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0031_auto_20230731_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('orcid_id', models.CharField(default='', help_text='Provide 16 digits orcid in the form: 0000-0000-0000-0000', max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Type of contribution', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='LabContributor',
        ),
        migrations.AddField(
            model_name='contributor',
            name='affiliation',
            field=models.ManyToManyField(help_text='Select one or several type for this contributor', to='rawdata_catalog.Type'),
        ),
    ]
