# Generated by Django 3.2.5 on 2023-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0034_auto_20230802_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
    ]
