# Generated by Django 3.2.5 on 2023-08-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0038_auto_20230802_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ManyToManyField(help_text='Select one or several affiliation for this contributor', to='rawdata_catalog.Affiliation')),
                ('origin', models.ManyToManyField(help_text='Select one or several origin for this contributor', to='rawdata_catalog.Origin')),
                ('person', models.ForeignKey(help_text='Select one person', on_delete=django.db.models.deletion.CASCADE, to='rawdata_catalog.person')),
                ('type', models.ManyToManyField(help_text='Select one or several type for this contributor', to='rawdata_catalog.Type')),
            ],
            options={
                'ordering': ['person'],
            },
        ),
    ]
