# Generated by Django 3.2.5 on 2023-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0039_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='department',
            field=models.CharField(default='', help_text='department name of the affiliation', max_length=200),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='institute_name',
            field=models.CharField(blank=True, help_text='Name of the institute for the affiliation', max_length=200),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='laboratory_name',
            field=models.CharField(blank=True, help_text='Name of the laboratory for the affiliation', max_length=200),
        ),
    ]
