# Generated by Django 3.2.5 on 2023-08-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0041_alter_affiliation_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ['short_name', 'laboratory']},
        ),
        migrations.RenameField(
            model_name='affiliation',
            old_name='institute_name',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='affiliation',
            old_name='laboratory_name',
            new_name='laboratory',
        ),
    ]
