# Generated by Django 3.2.5 on 2023-08-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0042_auto_20230802_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(help_text='Short name for treatment', max_length=200)),
                ('name_long', models.CharField(blank=True, help_text='Long name for treatment', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the treatment', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the contribution', max_length=1000),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='country',
            field=models.CharField(help_text='Country of the of affiliation', max_length=200),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department name of the affiliation', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid_id',
            field=models.CharField(blank=True, default='', help_text='Provide 16 digits orcid in the form: 0000-0000-0000-0000', max_length=19),
        ),
    ]
