# Generated by Django 3.2.5 on 2023-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0049_auto_20230804_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='laboratory_internal',
            field=models.CharField(blank=True, help_text='Internal name of the laboratory for the affiliation', max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.CharField(choices=[('microscopy/in_vitro', 'Microscopy, in-vitro'), ('microscopy/in_vivo', 'Microscopy, in-vivo'), ('sequencing/CUTandTAG', 'Sequencing, Cut&Tag'), ('sequencing/scRNA-seq', 'Sequencing, scRNA'), ('sequencing/scMultiome-seq', 'Sequencing, scMultiome')], default='', help_text='Type of experiment', max_length=100),
        ),
    ]
