# Generated by Django 3.2.5 on 2023-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0050_auto_20230804_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the experiment', max_length=1000),
        ),
        migrations.AddField(
            model_name='experiment',
            name='treatment',
            field=models.ManyToManyField(help_text='Select treatments for this experiment', to='rawdata_catalog.Treatment'),
        ),
    ]
