# Generated by Django 3.2.5 on 2023-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0054_experiment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(help_text='Short name for the experimental tag', max_length=200)),
                ('name_long', models.CharField(blank=True, help_text='Long name the experimental tag', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the experimental tag', max_length=1000)),
            ],
            options={
                'verbose_name': 'Experimental tag',
                'verbose_name_plural': 'Experimental tags',
            },
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='type',
            new_name='data type',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('published', 'Published'), ('paused', 'Paused'), ('finished', 'Finished'), ('terminated', 'Terminated')], default='Ongoing', help_text='Status of the experiment', max_length=100),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='treatment',
            field=models.ManyToManyField(blank=True, help_text='Select treatment(s) for this experiment', to='rawdata_catalog.Treatment'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='exptags',
            field=models.ManyToManyField(help_text='Select experimental tag(s) for this experiment', to='rawdata_catalog.ExperimentalTag'),
        ),
    ]
