# Generated by Django 3.2.5 on 2023-08-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0058_auto_20230804_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zenodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the zenodo entry', max_length=1000)),
                ('doi', models.CharField(help_text='Provide the zenodo DOI in the form: 10.5281/zenodo.7584090', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='zenodo',
            field=models.ManyToManyField(blank=True, help_text='Select zenodo(s) for this experiment', to='rawdata_catalog.Zenodo'),
        ),
    ]
