# Generated by Django 3.2.5 on 2023-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0059_auto_20230804_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenodo',
            name='doi',
            field=models.CharField(help_text='Provide the zenodo DOI in the form: 10.5281/zenodo.8211680', max_length=200),
        ),
    ]
