# Generated by Django 3.2.5 on 2023-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0062_auto_20230805_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='name of the project, should reflect the name on the RCP storage', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(help_text='Name of the experiment, should reflect the name on the RCP storage', max_length=100),
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ManyToManyField(blank=True, help_text='Choose one or several project(s) to which this experiment belong', to='rawdata_catalog.Project'),
        ),
    ]
