# Generated by Django 3.2.5 on 2023-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0067_alter_publication_bioarxiv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
