# Generated by Django 3.2.5 on 2023-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0068_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='experiment_status',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='zenodo',
        ),
        migrations.AddField(
            model_name='project',
            name='experiments',
            field=models.ManyToManyField(blank=True, help_text='Choose one or several experiment(s) for this project', to='rawdata_catalog.Experiment'),
        ),
        migrations.AddField(
            model_name='project',
            name='publication',
            field=models.ManyToManyField(blank=True, help_text='Select publication(s) for this project', to='rawdata_catalog.Publication'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('published', 'Published'), ('paused', 'Paused'), ('finished', 'Finished'), ('terminated', 'Terminated')], default='Ongoing', help_text='Status of the project', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='zenodo',
            field=models.ManyToManyField(blank=True, help_text='Select zenodo(s) for this project', to='rawdata_catalog.Zenodo'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='data_type',
            field=models.CharField(choices=[('microscopy/in_vitro', 'Microscopy, in-vitro'), ('microscopy/in_vivo', 'Microscopy, in-vivo'), ('sequencing/CUTandTAG', 'Sequencing, Cut&Tag'), ('sequencing/scRNA-seq', 'Sequencing, scRNA'), ('sequencing/scMultiome-seq', 'Sequencing, scMultiome')], default='', help_text='Type of data. WARNING: should reflect the name on the RCP storage', max_length=100),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(help_text='Name of the experiment. WARNING: should reflect the name on the RCP storage', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(help_text='Date field in format: MM/DD/YYYY', null=True),
        ),
    ]
