# Generated by Django 3.2.5 on 2023-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0069_auto_20230807_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contribution',
            new_name='ExperimentalContribution',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='experimental_tags',
            new_name='experimental_tag',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='experiments',
            new_name='experiment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='contributions',
        ),
        migrations.AddField(
            model_name='experiment',
            name='contribution',
            field=models.ManyToManyField(help_text='Select contribution(s) for this experiment', to='rawdata_catalog.ExperimentalContribution'),
        ),
    ]
