# Generated by Django 3.2.5 on 2023-08-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0072_auto_20230810_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
