# Generated by Django 3.2.5 on 2023-08-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0075_auto_20230814_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentaldata',
            name='compression',
            field=models.CharField(choices=[('none', 'None'), ('jeraw', 'JetRaw'), ('zip', 'Zip'), ('tar', 'Tar')], default='none', help_text='Type of compression if any', max_length=100),
        ),
        migrations.AddField(
            model_name='experimentaldata',
            name='file_format',
            field=models.CharField(choices=[('none', 'None'), ('tiff', 'tiff'), ('nd2', 'nd2'), ('fastq', 'fastq')], default='none', help_text='Format of the files', max_length=100),
        ),
        migrations.AddField(
            model_name='experimentaldata',
            name='number_of_files',
            field=models.CharField(default='', help_text='Number of files for this dataset. FILLED AUTOMATICALLY', max_length=10),
        ),
        migrations.AddField(
            model_name='experimentaldata',
            name='total_size',
            field=models.CharField(default='', help_text='Total size for this dataset. FILLED AUTOMATICALLY', max_length=100),
        ),
    ]
