# Generated by Django 3.2.5 on 2023-08-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0076_auto_20230814_0810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperimentalData',
            new_name='ExperimentalDataset',
        ),
    ]
