# Generated by Django 3.2.5 on 2023-08-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0079_auto_20230814_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='experimentaldataset',
            name='compression',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('jeraw', 'JetRaw'), ('zip', 'Zip'), ('tar', 'Tar')], default='', help_text='Type of compression if any', max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentaldataset',
            name='data_type',
            field=models.CharField(choices=[('microscopy/in_vitro', 'Microscopy, in-vitro'), ('microscopy/in_vivo', 'Microscopy, in-vivo'), ('sequencing/CUTandTAG', 'Sequencing, Cut&Tag'), ('sequencing/scRNA-seq', 'Sequencing, scRNA'), ('sequencing/scMultiome-seq', 'Sequencing, scMultiome')], help_text='Type of data for this dataset (reflecting the the RCP storage categories)', max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentaldataset',
            name='file_format',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('tiff', 'tiff'), ('nd2', 'nd2'), ('fastq', 'fastq')], default='', help_text='Format of the files', max_length=100),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdata_catalog.blog')),
            ],
        ),
    ]
