# Generated by Django 3.2.5 on 2023-08-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0080_auto_20230815_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_name',
            field=models.CharField(choices=[('subname1', 'subname1'), ('subname2', 'subname2'), ('subname3', 'subname3'), ('subname4', 'subname4'), ('subname5', 'subname5')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(choices=[('name1', 'name1'), ('name2', 'name2'), ('name3', 'name3'), ('name4', 'name4'), ('name5', 'name5')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
