# Generated by Django 3.2.5 on 2023-08-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0081_auto_20230815_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentaldataset',
            name='experiment',
            field=models.ForeignKey(blank=True, default='', help_text='Select experimental datasets for this experiment', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rawdata_catalog.experiment'),
        ),
        migrations.AlterField(
            model_name='experimentaldataset',
            name='experimental_sample',
            field=models.ManyToManyField(blank=True, default='', help_text='Select experimental samples for this experimental dataset', null=True, to='rawdata_catalog.ExperimentalSample'),
        ),
    ]
