# Generated by Django 3.2.5 on 2023-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0083_auto_20230821_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdataset',
            name='files_data',
            field=models.JSONField(null=True),
        ),
    ]
