# Generated by Django 3.2.5 on 2023-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata_catalog', '0084_rawdataset_files_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdataset',
            name='date_added',
            field=models.DateField(help_text='Date automatically registered (when pushing the refresh button)', null=True),
        ),
    ]
