# Generated by Django 3.2.5 on 2023-10-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0004_auto_20231006_1619'),
        ('analysis_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the analysis', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ('name', 'start_date'), 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AddField(
            model_name='analysis',
            name='start_date',
            field=models.DateField(help_text='Starting date of the analysis.', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the analysis', max_length=2000),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(help_text='Name of the analysis', max_length=100),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(help_text='Select one project for this analysis, if it does not exist, it needs to be created', on_delete=django.db.models.deletion.CASCADE, to='project_catalog.project'),
        ),
    ]
