# Generated by Django 3.2.5 on 2023-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_catalog', '0002_auto_20231026_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='end_date',
            field=models.DateField(blank=True, help_text='Starting date of the analysis.', null=True),
        ),
    ]
