# Generated by Django 3.2.5 on 2023-10-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_catalog', '0003_analysis_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('paused', 'Paused'), ('finished', 'Finished'), ('stopped', 'Stopped')], default='Ongoing', help_text='Status of the analysis', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the analysis in format: MM/DD/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='start_date',
            field=models.DateField(help_text='Start date of the analysis in format: MM/DD/YYYY', null=True),
        ),
    ]
