# Generated by Django 3.2.5 on 2023-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_catalog', '0005_auto_20231027_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistag',
            options={'ordering': ('name',), 'verbose_name': 'Analysis tag', 'verbose_name_plural': 'Analysis tags'},
        ),
        migrations.AddField(
            model_name='analysisdataset',
            name='files',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='analysisstep',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the analysis', max_length=2000),
        ),
        migrations.AddField(
            model_name='analysisstep',
            name='input_dataset',
            field=models.ManyToManyField(help_text='Input dataset', related_name='input_dataset', to='analysis_catalog.AnalysisDataset'),
        ),
        migrations.AddField(
            model_name='analysisstep',
            name='output_dataset',
            field=models.ManyToManyField(help_text='Output dataset', related_name='output_dataset', to='analysis_catalog.AnalysisDataset'),
        ),
        migrations.AlterField(
            model_name='analysisdataset',
            name='path',
            field=models.CharField(help_text='Path of the analysis dataset inside upoates rcp share', max_length=200),
        ),
        migrations.AlterField(
            model_name='analysisstep',
            name='name',
            field=models.CharField(help_text='Name of the analysis step', max_length=100),
        ),
    ]
