# Generated by Django 3.2.5 on 2023-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_catalog', '0006_auto_20231030_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisstep',
            name='step_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Analysis step number'),
        ),
    ]
