# Generated by Django 3.2.5 on 2023-10-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_catalog', '0007_analysisstep_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisstep',
            name='analysis',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analysis_catalog.analysis'),
        ),
    ]
