# Generated by Django 3.2.5 on 2023-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_catalog', '0008_analysisstep_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdataset',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisdataset',
            name='number_of_files',
            field=models.CharField(blank=True, help_text='Path of the analysis dataset', max_length=200),
        ),
        migrations.AlterField(
            model_name='analysisdataset',
            name='total_size',
            field=models.CharField(blank=True, help_text='Path of the analysis dataset', max_length=200),
        ),
    ]
