# Generated by Django 3.2.5 on 2023-11-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_catalog', '0009_auto_20231030_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisdataset',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='analysisstep',
            options={'ordering': ('analysis__name', 'step_number')},
        ),
        migrations.AlterField(
            model_name='analysisstep',
            name='analysis',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis_catalog.analysis'),
        ),
        migrations.AlterField(
            model_name='analysisstep',
            name='output_dataset',
            field=models.ManyToManyField(blank=True, help_text='Output dataset', related_name='output_dataset', to='analysis_catalog.AnalysisDataset'),
        ),
    ]
