# Generated by Django 3.2.5 on 2023-11-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0006_auto_20231027_0759'),
        ('analysis_catalog', '0010_auto_20231101_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(help_text='Select one project for this analysis, if it does not exist, it needs to be created', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_project', to='project_catalog.project'),
        ),
        migrations.AlterField(
            model_name='analysisstep',
            name='input_dataset',
            field=models.ManyToManyField(blank=True, help_text='Input dataset', related_name='input_dataset', to='analysis_catalog.AnalysisDataset'),
        ),
    ]
