# Generated by Django 3.2.5 on 2023-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20230731_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='laboratory_name',
            field=models.CharField(help_text='Name of the laboratory for the affiliation', max_length=200),
            preserve_default=False,
        ),
    ]
