# Generated by Django 3.2.5 on 2023-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20230731_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labcontributor',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='labcontributor',
            name='orcid_id',
            field=models.CharField(default='', help_text='Provide 16 digits orcid in the form: 0000-0000-0000-0000', max_length=100),
        ),
    ]
