# Generated by Django 3.2.5 on 2023-08-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20230802_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ['short_name', 'laboratory_name']},
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='start_date',
        ),
    ]
