# Generated by Django 3.2.5 on 2023-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20230802_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='origin',
            field=models.ManyToManyField(help_text='Select one or several origin for this contributor', to='catalog.Origin'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='type',
            field=models.ManyToManyField(help_text='Select one or several type for this contributor', to='catalog.Type'),
        ),
    ]
