# Generated by Django 3.2.5 on 2023-08-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20230802_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='department',
            field=models.CharField(blank=True, default='', help_text='department name of the affiliation', max_length=200),
        ),
    ]
