# Generated by Django 3.2.5 on 2023-08-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20230803_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={},
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email_address',
        ),
        migrations.AddField(
            model_name='contributor',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
