# Generated by Django 3.2.5 on 2023-08-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20230803_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the contribution for this contributor', max_length=1000)),
                ('contributor', models.ManyToManyField(help_text='Select a contributor', to='catalog.Contributor')),
                ('origin', models.ManyToManyField(help_text='Select one or several origin of contribution for this contributor', to='catalog.Origin')),
                ('type', models.ManyToManyField(help_text='Select one or several type of contribution for this contributor', to='catalog.Type')),
            ],
        ),
    ]
