# Generated by Django 3.2.5 on 2023-08-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_rename_orcid_id_person_orcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='type',
        ),
        migrations.AddField(
            model_name='contribution',
            name='type',
            field=models.CharField(blank=True, choices=[('microscopy', 'Microscopy'), ('sequencing', 'Sequencing')], default='', help_text='Type of the experiment', max_length=100),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the experiment, should reflect the name on the RCP storage', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the contribution for this contributor', max_length=1000)),
                ('contributions', models.ManyToManyField(help_text='Select contributions', to='catalog.Contribution')),
                ('origin', models.ManyToManyField(help_text='Select one or several origin of contribution for this contributor', to='catalog.Origin')),
                ('type', models.ManyToManyField(help_text='Select one or several type of contribution for this contributor', to='catalog.Type')),
            ],
        ),
    ]
