# Generated by Django 3.2.5 on 2023-08-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20230804_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='type',
        ),
    ]
