# Generated by Django 3.2.5 on 2023-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_auto_20230804_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='type',
            field=models.CharField(blank=True, choices=[('microscopy', 'Microscopy'), ('sequencing', 'Sequencing')], default='d', help_text='Book availability', max_length=100),
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='type',
        ),
        migrations.AddField(
            model_name='contribution',
            name='type',
            field=models.ManyToManyField(help_text='Select one or several type of contribution for this contributor', to='catalog.Type'),
        ),
    ]
