# Generated by Django 3.2.5 on 2023-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_auto_20230804_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Edited Address', 'verbose_name_plural': 'Edited Addresses'},
        ),
        migrations.AlterField(
            model_name='experiment',
            name='contributions',
            field=models.ManyToManyField(help_text='Select contribution(s) for this experiment', to='catalog.Contribution'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='treatment',
            field=models.ManyToManyField(help_text='Select treatment(s) for this experiment', to='catalog.Treatment'),
        ),
    ]
