# Generated by Django 3.2.5 on 2023-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20230804_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origin',
            options={'verbose_name': 'Origin of the contribution', 'verbose_name_plural': 'Origin of the contributions'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type of contribution', 'verbose_name_plural': 'Type of contributions'},
        ),
        migrations.AddField(
            model_name='experiment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='origin',
            field=models.CharField(help_text='Origin of the contribution', max_length=200),
        ),
    ]
