# Generated by Django 3.2.5 on 2023-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_rename_data type_experiment_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(help_text='Short name for the publication', max_length=200)),
                ('bioarxiv_id', models.CharField(help_text='Bioarxiv id for the publication using a specific experiment', max_length=200)),
                ('bioarxiv_title', models.CharField(help_text='Bioarxiv title for the publication using a specific experiment', max_length=200)),
                ('journal_id', models.CharField(blank=True, help_text='Journal id for the publication using a specific experiment', max_length=200)),
                ('journal_title', models.CharField(blank=True, help_text='Journal title for the publication using a specific experiment', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='publication',
            field=models.ManyToManyField(blank=True, help_text='Select publication(s) for this experiment', to='catalog.Publication'),
        ),
    ]
