# Generated by Django 3.2.5 on 2023-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_alter_zenodo_doi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='name',
            new_name='experiment_name',
        ),
        migrations.AddField(
            model_name='experiment',
            name='project_name',
            field=models.CharField(default='', help_text='name of the project, should reflect the name on the RCP storage', max_length=100),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='data_type',
            field=models.CharField(choices=[('microscopy/in_vitro', 'Microscopy, in-vitro'), ('microscopy/in_vivo', 'Microscopy, in-vivo'), ('sequencing/CUTandTAG', 'Sequencing, Cut&Tag'), ('sequencing/scRNA-seq', 'Sequencing, scRNA'), ('sequencing/scMultiome-seq', 'Sequencing, scMultiome')], default='', help_text='Type of experiment, reflect the name on the RCP storage', max_length=100),
        ),
    ]
