# Generated by Django 3.2.5 on 2023-08-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_auto_20230806_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the project', max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', help_text='Name of the project', max_length=200),
        ),
        migrations.AlterField(
            model_name='experimentaltag',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the experimental tag', max_length=2000),
        ),
        migrations.AlterField(
            model_name='zenodo',
            name='doi',
            field=models.CharField(help_text='Provide the zenodo DOI in the form: 10.5281/zenodo.8211680', max_length=40),
        ),
        migrations.AlterField(
            model_name='zenodo',
            name='title',
            field=models.CharField(help_text='Title for the zenodo entry', max_length=200),
        ),
    ]
