# Generated by Django 3.2.5 on 2023-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_alter_experiment_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='bioarxiv_id',
            field=models.CharField(help_text='Bioarxiv id for the publication using a specific experiment in the form e.g.: 2023.08.02.551629v2', max_length=200),
        ),
    ]
