# Generated by Django 3.2.5 on 2023-08-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_delete_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(help_text='Short name for injection', max_length=200)),
                ('name_long', models.CharField(blank=True, help_text='Long name for injection', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the injection', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(help_text='Short name for the project tag', max_length=200)),
                ('name_long', models.CharField(blank=True, help_text='Long name the project tag', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the project tag', max_length=2000)),
            ],
            options={
                'verbose_name': 'Project tag',
                'verbose_name_plural': 'Project tags',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='injection',
            field=models.ManyToManyField(blank=True, help_text='Select injection(s) for this experiment', to='catalog.Injection'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tag',
            field=models.ManyToManyField(help_text='Select project tag(s) for this experiment', to='catalog.ProjectTag'),
        ),
    ]
