# Generated by Django 3.2.5 on 2023-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20230810_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('microscopy/in_vitro', 'Microscopy, in-vitro'), ('microscopy/in_vivo', 'Microscopy, in-vivo'), ('sequencing/CUTandTAG', 'Sequencing, Cut&Tag'), ('sequencing/scRNA-seq', 'Sequencing, scRNA'), ('sequencing/scMultiome-seq', 'Sequencing, scMultiome')], default='', help_text='Type of data (reflecting the the RCP storage categories)', max_length=100)),
                ('rcp_name', models.CharField(help_text='Name of the experiment folder on the RCP storage.', max_length=100)),
                ('data_status', models.CharField(choices=[('available', 'Available'), ('notavailable', 'Not available'), ('deleted', 'Deleted')], default='', help_text='Status of the data on the RCP storage', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Origin',
            new_name='ContributionOrigin',
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='ContributionType',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='data_status',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='data_type',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='contribution',
            field=models.ManyToManyField(blank=True, help_text='Select contribution(s) for this experiment', to='catalog.ExperimentalContribution'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='date',
            field=models.DateField(help_text='date the experiment is done', null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(help_text='Name of the experiment.', max_length=100),
        ),
    ]
