# Generated by Django 3.2.5 on 2023-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_auto_20230814_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='experimentaldataset',
            name='data_type',
            field=models.CharField(choices=[('none', 'None'), ('microscopy/in_vitro', 'Microscopy, in-vitro'), ('microscopy/in_vivo', 'Microscopy, in-vivo'), ('sequencing/CUTandTAG', 'Sequencing, Cut&Tag'), ('sequencing/scRNA-seq', 'Sequencing, scRNA'), ('sequencing/scMultiome-seq', 'Sequencing, scMultiome')], default='none', help_text='Type of data for this dataset (reflecting the the RCP storage categories)', max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentaldataset',
            name='rcp_name',
            field=models.CharField(choices=[('her1_Dr_GFPpoly_S17', 'her1_Dr_GFPpoly_S17'), ('her1_Dr_H2AZ_S19', 'her1_Dr_H2AZ_S19'), ('her1_Dr_Neg_S20', 'her1_Dr_Neg_S20'), ('her1_Dr_VenusAb_S18', 'her1_Dr_VenusAb_S18'), ('her7_Dr_GFPpoly_S1', 'her7_Dr_GFPpoly_S1'), ('her7_Dr_H2AZ_S3', 'her7_Dr_H2AZ_S3'), ('her7_Dr_Neg_S4', 'her7_Dr_Neg_S4'), ('her7_Dr_Venus_S2', 'her7_Dr_Venus_S2'), ('ppf001_well1', 'ppf001_well1'), ('ppf001_well2', 'ppf001_well2'), ('ppf001_well3', 'ppf001_well3'), ('wildtype_scm_001_01', 'wildtype_scm_001_01'), ('wildtype_scm_001_02', 'wildtype_scm_001_02'), ('wildtype_scm_001_03', 'wildtype_scm_001_03'), ('wildtype_scm_001_04', 'wildtype_scm_001_04'), ('wildtype_scm_001_05', 'wildtype_scm_001_05'), ('wildtype_scm_001_06', 'wildtype_scm_001_06'), ('wildtype_scr_001', 'wildtype_scr_001'), ('wildtype_scr_002', 'wildtype_scr_002'), ('wildtype_scr_003', 'wildtype_scr_003'), ('wildtype_scr_004', 'wildtype_scr_004'), ('wildtype_scr_005_01', 'wildtype_scr_005_01'), ('wildtype_scr_005_02', 'wildtype_scr_005_02'), ('wildtype_scr_005_03', 'wildtype_scr_005_03'), ('wildtype_scr_005_04', 'wildtype_scr_005_04'), ('wildtype_scr_006_01', 'wildtype_scr_006_01'), ('wildtype_scr_006_02', 'wildtype_scr_006_02'), ('wildtype_scr_006_03', 'wildtype_scr_006_03'), ('wildtype_scr_006_04', 'wildtype_scr_006_04'), ('wscepfl060_well1', 'wscepfl060_well1'), ('wscepfl060_well1', 'wscepfl060_well1'), ('wscepfl060_well2', 'wscepfl060_well2')], help_text='Name of the experimental dataset folder on the RCP storage.', max_length=100),
        ),
        migrations.AddField(
            model_name='experimentaldataset',
            name='experimental_sample',
            field=models.ManyToManyField(default='', help_text='Select experimental samples for this experimental dataset', null=True, to='catalog.ExperimentalSample'),
        ),
    ]
